---
- name: Configure docker 
  hosts: [deployserver]
  become: true
  connection: ssh

  tasks:
    - name: Update apt
      apt-get: 
       name: Update
       state: present

    - name: Install docker
      apt: 
       name: docker.io
       state: present

    - name: Start the docker service
      become: true
      service:
        name: docker
        state: started

    - name: Run the docker image
      docker_container:
        name: Insureme
        image: annapoornakaradi/project1_insureme:latest
        state: started
        recreate: yes
        expose:
          - 8081
          - 8080
        ports:
          - "8080:8081"


